import { defineApp } from "@slflows/sdk/v1";
import { blocks } from "./blocks";

export const app = defineApp({
  name: "GCP Toolkit",
  installationInstructions: `## Authentication Methods

Choose **one** of these authentication methods:

### Option 1: Service Account Key (Simpler Setup)

1. Go to [GCP Console → IAM & Admin → Service Accounts](https://console.cloud.google.com/iam-admin/serviceaccounts)
2. Create or select a service account with required permissions
3. Click **Keys** → **Add Key** → **Create New Key** → **JSON**
4. Download the JSON file
5. Fill in the configuration:
   - **Project ID**: Copy the \`project_id\` field from the JSON
   - **Service Account Key**: Paste the entire JSON contents
   - **Service Account Email**: Copy the \`client_email\` field from the JSON

### Option 2: Access Token (Recommended for Production)

For better security, use short-lived access tokens via Workload Identity Federation:

1. Install the **GCP Workload Identity Federation** app in your Flows workspace
2. Configure it with your OIDC provider (GitHub, GitLab, etc.)
3. Fill in the configuration:
   - **Project ID**: Your GCP project ID (find in [GCP Console](https://console.cloud.google.com) or run \`gcloud config get-value project\`)
   - **Access Token**: Generated by the Workload Identity Federation app
   - **Service Account Email**: Find in [GCP Console → Service Accounts](https://console.cloud.google.com/iam-admin/serviceaccounts)

This approach eliminates long-lived credentials and provides better security and audit trails.`,
  blocks,
  config: {
    projectId: {
      name: "Project ID",
      description: `Your GCP Project ID (e.g., \`my-project-123\`)

Find this in the [GCP Console](https://console.cloud.google.com) or run:
\`\`\`bash
gcloud config get-value project
\`\`\``,
      type: "string",
      required: true,
    },
    serviceAccountEmail: {
      name: "Service Account Email",
      description: `The email address of the service account e.g., \`my-sa@project-id.iam.gserviceaccount.com\``,
      type: "string",
      required: true,
      sensitive: false,
    },
    serviceAccountKey: {
      name: "Service Account Key",
      description: `**Long-lived credentials** (optional if using Access Token below)

Provide your GCP Service Account JSON key file contents.

**To create:**
1. Go to [GCP Console → IAM & Admin → Service Accounts](https://console.cloud.google.com/iam-admin/serviceaccounts)
2. Create or select a service account with appropriate permissions
3. Click **Keys** → **Add Key** → **Create New Key** → **JSON**
4. Download the JSON file and paste its entire contents here

**Not required** if you're using the **Access Token** field below.`,
      type: "string",
      required: false,
      sensitive: true,
    },
    accessToken: {
      name: "Access Token",
      description: `**Short-lived token** (optional if using Service Account Key above)

Provide a pre-generated GCP access token for keyless authentication.

**Recommended approach:** Use the **GCP Workload Identity Federation** app to generate short-lived tokens via OIDC. This is more secure than long-lived service account keys.

**Not required** if you're using the **Service Account Key** field above.

**Important:** If using Access Token, you must also provide the **Service Account Email** below.`,
      type: "string",
      required: false,
      sensitive: true,
    },
  },
});
